package com.example.myapplication.utils

import com.example.myapplication.R
import com.example.myapplication.model.Post
import com.example.myapplication.model.User

object DataMocks {

    val currentUser = User(
        1u,
        "Todd Howard",
        R.drawable.profilepic,
        10u,
        3u,
        14u,
        "Game director of Bethesda Game Studios. Creator of Skyrim and recursive functions which helped with recursive functions which helped with recursive functions which helped with recursive functions which helped with recursive functions which helped with recursive functions."
    )
    
    val textSamples = listOf("Mauris non ante id massa elementum lobortis.",
            "Morbi faucibus eros sit amet lectus convallis mollis sed sit amet nisi.",
            "Mauris et turpis a urna luctus scelerisque.",
            "Nullam quis risus ut odio laoreet dictum.",
            "Etiam pellentesque velit id ipsum placerat ornare.",
            "Quisque venenatis lacus nec sem pharetra aliquam.",
            "Curabitur facilisis nunc pellentesque augue lacinia, vitae placerat nibh dictum.",
            "Aliquam vel dolor sit amet sem eleifend pharetra vel non enim.",
            "Donec eget diam quis felis varius rutrum.",
            "Mauris viverra mauris at mauris vulputate, ac fermentum quam luctus.",
            "Phasellus vitae ante eu ex efficitur tincidunt.",
            "Morbi eget odio porta sapien ullamcorper ultrices.",
            "Etiam sit amet felis lacinia, interdum massa vel, pretium eros.",
            "Donec quis turpis sit amet nibh aliquam facilisis.",
            "Phasellus eleifend felis et urna dignissim varius.",
            "Sed sagittis sapien molestie mauris tempus fringilla.",
            "Vivamus at velit iaculis, consectetur felis in, imperdiet est.",
            "Quisque vitae sapien at magna viverra vehicula non et sem.",
            "Nam rutrum mauris quis velit sollicitudin ultrices.",
            "Vivamus vitae enim a mauris tempor egestas.",
            "Duis consectetur justo ac augue aliquam lobortis.",
            "Duis suscipit dui non dui placerat, non lacinia diam mollis.",
            "Nunc et libero dapibus, maximus diam malesuada, bibendum ligula.",
            "Nullam et nulla eu enim mollis tempus.",
            "Nulla quis dolor et nulla venenatis facilisis.",
            "Etiam id purus eget quam tempor efficitur.",
            "Nulla feugiat arcu non efficitur finibus.",
            "Nam ultrices purus vel dui tincidunt sollicitudin.",
            "Morbi tincidunt odio quis velit finibus varius.",
            "Sed ornare odio ac maximus suscipit.",
            "Proin rutrum mi molestie urna pretium venenatis.",
            "Proin quis justo tristique, ultrices sem in, imperdiet lectus.",
            "Nam at libero suscipit, auctor ex a, finibus dolor.",
            "Duis sed est nec lectus facilisis congue.",
            "Pellentesque eget elit eget velit vestibulum consequat eget id quam.",
            "Suspendisse ut nisl laoreet, pellentesque leo a, luctus sem.",
            "Curabitur ut nulla et risus lacinia pharetra.",
            "Morbi placerat nunc sed erat rutrum aliquam.",
            "Nunc vel neque interdum ligula sagittis tempor at in eros.",
            "Nam tristique neque id neque porta porttitor.",
            "Cras elementum tellus ut justo venenatis sagittis.",
            "Ut commodo nisl quis metus facilisis, vel laoreet nulla luctus.",
            "Aenean ut tortor consequat, convallis tortor in, fermentum sapien.",
            "Vivamus interdum lacus quis vestibulum posuere.",
            "Praesent ac est vitae lorem dapibus placerat ac in mauris.",
            "Vivamus convallis diam elementum urna rutrum, sed pulvinar velit bibendum.",
            "Donec eget neque id leo mattis facilisis eget sit amet sem.",
            "Morbi ut risus facilisis, tristique orci in, efficitur nisi.",
            "Quisque feugiat purus ac varius lacinia.",
            "Nullam ornare nibh eu ipsum lacinia sagittis.",
            "Sed rutrum nulla eu est pharetra, sit amet ultricies erat dignissim.",
            "Praesent sit amet risus ut orci sagittis tincidunt sit amet nec est.",
            "Nam et eros vitae diam mattis dapibus.",
            "Phasellus facilisis neque sed arcu efficitur convallis.",
            "Vivamus scelerisque purus in purus ornare, et euismod sem aliquam.",
            "Nullam in leo ac nibh ultrices tristique.",
            "Vivamus efficitur purus vitae blandit efficitur.",
            "Aenean eget augue iaculis, ornare arcu a, feugiat nisi.",
            "Fusce sed sapien in nulla gravida varius at ac enim.",
            "Proin sed orci sagittis, feugiat turpis ut, rhoncus arcu.",
            "Fusce vel lectus ut augue vestibulum euismod.",
            "Donec ac risus vel mi aliquam consectetur.",
            "Donec iaculis odio id quam ultricies, id viverra risus ornare.",
            "Donec feugiat diam vel mattis dictum.",
            "Ut laoreet tellus ut imperdiet sodales.",
            "Praesent vitae ante in mi malesuada lobortis eu rutrum elit.",
            "Pellentesque vel erat pellentesque odio pellentesque ultrices quis at ipsum.",
            "Suspendisse maximus velit sed iaculis tempor.",
            "Ut euismod augue quis arcu consequat posuere a ac ipsum.",
            "Donec euismod nunc ac ex vulputate, vitae porttitor erat pellentesque.",
            "Curabitur et lectus ornare, rutrum risus eu, lobortis dui.",
            "Donec venenatis est elementum felis scelerisque, ac fermentum ipsum laoreet.",
            "Sed tempus metus id velit malesuada accumsan.",
            "Duis nec lectus vestibulum, ullamcorper lectus eget, posuere sem.",
            "Cras sit amet libero gravida, vulputate tellus eget, faucibus odio.",
            "Nulla quis dolor nec turpis sodales consectetur ac at nibh.",
            "Proin porta sapien quis mattis feugiat.",
            "Aenean pellentesque leo vel ipsum bibendum, sit amet tempor diam commodo.",
            "Nam semper mauris at felis cursus, non vehicula quam posuere.",
            "Pellentesque porta ante at nunc sollicitudin, quis mollis eros malesuada.",
            "Nulla fringilla ligula vel dignissim porttitor.",
            "Mauris et augue vel leo blandit tincidunt.",
            "Nulla auctor justo eget ultrices rhoncus.",
            "Nulla vel enim posuere, dictum turpis id, interdum magna.",
            "Nunc id erat et ipsum commodo dapibus quis sit amet leo.",
            "Nullam faucibus eros quis feugiat faucibus.",
            "Maecenas at quam blandit dolor finibus ultricies vel tincidunt justo.",
            "Curabitur in velit hendrerit, ornare sapien id, pharetra nulla.",
            "Curabitur in purus a nulla feugiat rhoncus.",
            "Ut aliquam nibh aliquam cursus rhoncus.",
            "Suspendisse sed erat varius, dignissim enim vel, bibendum dolor.",
            "Proin pulvinar leo in justo pellentesque, ac interdum velit vehicula.",
            "Mauris interdum neque at tellus sagittis, a posuere ipsum eleifend.",
            "Donec eleifend nisl sit amet odio facilisis, ac mattis eros molestie.",
            "Curabitur sit amet urna non lacus placerat finibus nec sed orci.",
            "Fusce id erat vitae dui scelerisque aliquam in ullamcorper urna.",
            "In ac libero sagittis, dapibus ligula non, laoreet ipsum.",
            "Nulla eleifend neque eget fermentum accumsan.",
            "Aliquam pellentesque ex id arcu feugiat, non luctus nibh ullamcorper.",
            "Quisque nec nisi ultrices, sodales justo et, vestibulum velit.",
            "Nulla at ex fermentum, maximus tortor a, facilisis erat.",
            "Maecenas efficitur ipsum a nibh imperdiet dictum.",
            "Pellentesque a diam quis mi faucibus ultrices.",
            "Vestibulum sodales sem ac facilisis sagittis.",
            "Etiam commodo magna vitae elit suscipit pulvinar.")

    val postsList = List(30) {
        Post(
            null,
            it.toUInt(),
            1u,
                currentUser.name,
            "${it + 1} Dec 2020",
            textSamples[it]
        )
    }
}